AnlisisNumericoWeb/Controllers/CurvasController.cs
using AnlisisNumericoWeb.Models;
using AnlisisNumericoWeb.Service;
using DynamicExpresso;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Reflection;

namespace AnlisisNumericoWeb.Controllers
{
    public class CurvasController : Controller
    {
        private readonly CurvasService _service = new();

        public IActionResult Index()
        {
            var curvasmodel = new CurvasModel();

            return View(curvasmodel);
        }

        [HttpPost]
        public IActionResult Calcular(CurvasModel model)
        {
            try
            {
                model.Resultado = _service.Calcular(model.Puntos, model.TipoAjuste , 5);
          
            }catch (Exception ex) 
            {
                ViewBag.Error = ex.Message;
            }

            return View("Index", model);
        }
    }
}

AnlisisNumericoWeb/Controllers/EcuacionesController.cs
using Microsoft.AspNetCore.Mvc;
using AnlisisNumericoWeb.Models;
using AnlisisNumericoWeb.Service;
using System;
using System.Globalization;

namespace AnlisisNumericoWeb.Controllers
{
    public class EcuacionesController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            // Inicializa una matriz 3x3 con ceros y un vector independiente con ceros
            var model = new EcuacionesModel
            {
                Matriz = Enumerable.Range(0, 4)
                                   .Select(_ => Enumerable.Repeat(0.0, 4).ToList())
                                   .ToList(),
                VectorIndependiente = Enumerable.Repeat(0.0, 4).ToList(),
                Incognitas = Enumerable.Repeat(0.0, 4).ToList()
            };

            return View("GaussJordan", model);
        }

        [HttpPost]
        public IActionResult Ajustar(int size)
        {
            var model = new EcuacionesModel
            {
                Matriz = Enumerable.Range(0, size)
                       .Select(_ => Enumerable.Repeat(0.0, size).ToList())
                       .ToList(),
                VectorIndependiente = Enumerable.Repeat(0.0, size).ToList(),
                Incognitas = Enumerable.Repeat(0.0, size).ToList()
            };

            return View("GaussJordan", model);
        }

        [HttpPost]
        public IActionResult Resolver(EcuacionesModel model)
        {
            try
            {
                if (model.Matriz == null || model.VectorIndependiente == null)
                    throw new Exception("Datos incompletos");

                if (model.Matriz.Count != model.VectorIndependiente.Count)
                    throw new Exception("La cantidad de filas de la matriz y del vector no coincide");

                List<double> resultado;

                if (model.Metodo.ToLower() == "gauss-jordan")
                {
                    resultado = EcuacionesService.SistemasEcuaciones.GaussJordan(
                        model.Matriz,
                        model.VectorIndependiente
                    );
                }
                else if (model.Metodo.ToLower() == "gauss-seidel")
                {
                    resultado = EcuacionesService.SistemasEcuaciones.GaussSeidel(
                        model.Matriz,
                        model.VectorIndependiente,
                        model.Tolerancia,
                        model.Iteraciones
                    );
                }
                else
                {
                    throw new Exception("Método no válido.");
                }

                model.Incognitas = resultado;
                ViewBag.Solucion = resultado;
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Ocurrió un error al resolver el sistema: " + ex.Message;
            }

            return View("GaussJordan", model);
        }
    }
}

AnlisisNumericoWeb/Controllers/IntegracionController.cs
using Microsoft.AspNetCore.Mvc;
using AnlisisNumericoWeb.Models;
using AnlisisNumericoWeb.Service;
using System;
using System.Globalization;
using NCalc;

namespace AnlisisNumericoWeb.Controllers
{
    public class IntegracionController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Resultado(IntegracionModel model)
        {
           
                model.Resultado = CalcularIntegral(model);
           

            return View("Resultado", model); // Asegurate de tener una vista Resultado.cshtml
        }
        private double EvaluarFuncion(string funcion, double x)
        {
            var expr = new Expression(funcion);
            expr.Parameters["x"] = x;
            return Convert.ToDouble(expr.Evaluate());
        }

        private double CalcularIntegral(IntegracionModel model)
        {
            var service = new IntegracionService();

            var result =   service.Calcular(model);
            model.Resultado = result;  

            return result;  
        }

    }
}

AnlisisNumericoWeb/Controllers/RaicesController.cs
using AnlisisNumericoWeb.Models;
using AnlisisNumericoWeb.Service;
using DynamicExpresso;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Reflection;


namespace AnlisisNumericoWeb.Controllers
{
    public class RaicesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public IActionResult Biseccion()
        {

            return View();
        }

        [HttpGet]
        public IActionResult ReglaFalsa()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Tangente()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Secante()
        {
            return View();
        }


        [HttpPost("Calcular")]
        public IActionResult Calcular(string metodo, RaizData model)
        {
            if (!ModelState.IsValid)
            {
                return View(metodo, model);
            }
            var func = model.Funcion.Replace("f(x) = ", "").Replace(" ", "");


            Func<double, double> funcion; 
            try
            {
                funcion = ParseFunc(func);

            }catch(Exception ex)
            {
                ViewBag.Error = "Ocurrió un error: Funcion incorrecta";

                return View(metodo, model);
            }
      
            try
            {
                var raiz = RaicesService.BuscarRaiz(funcion, metodo,model);

                model.Raiz = raiz;

                return View(metodo, model);
            }
            catch(Exception ex)
            {
                ViewBag.Error = "Ocurrió un error: " + ex.Message;
                return View(metodo,model);
            }

      
        }
    


        public Func<double, double> ParseFunc(string func)
        {
            var interpreter = new Interpreter();
   
            var function = interpreter.ParseAsDelegate<Func<double, double>>(func, "x");
            //Debug.WriteLine(function(5));
            return function;
        }   


}
}

AnlisisNumericoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AnlisisNumericoWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Raices.css" />
    <link rel="stylesheet" href="~/AnlisisNumericoWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="menu-container">
            <div class="menu-item" onclick="toggleSubmenu()">Raíces de funciones ▾</div>

            <!-- Usar div en vez de <a> para envolver -->
            <div class="sub-menu" id="submenu" style="display: none; margin-left: 20px;">
                <a class="menu-item" asp-controller="Raices" asp-action="Biseccion">Bisección</a>
                <a class="menu-item" asp-controller="Raices" asp-action="ReglaFalsa">Regla Falsa</a>
                <a class="menu-item" asp-controller="Raices" asp-action="Tangente">Newton-Raphson</a>
                <a class="menu-item" asp-controller="Raices" asp-action="Secante">Secante</a>
            </div>
            <a class="menu-item" asp-controller="Ecuaciones" asp-action="Index">Ecuaciones ▾</a>
            <a class="menu-item" asp-controller="Curvas" asp-action="Index">Curvas ▾</a>
            <a class="menu-item" asp-controller="Integracion" asp-action="Index">Integración ▾</a>
        </div>
    </header>
    @if (ViewBag.Error != null)
    {
        <div class="alert alert-danger">
            @ViewBag.Error
        </div>
    }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

</html>
<script src="~/js/Raices.js"></script>